services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development    
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    comm]]]]and: npm run start:dev
    ports:
      - 3000:3000   